#!/bin/sh
set -e

NAME=emc2101
VERSION=@VERSION@

case "$1" in
remove|upgrade|deconfigure)
	if [ -n "$(dkms status -m "$NAME" -v "$VERSION")" ]; then
		dkms remove -m "$NAME" -v "$VERSION" --all
	fi
	;;
esac

exit 0
